[package]
name = "opencl_std_math_vec-opencl"
edition.workspace = true

[lints]
workspace = true

# Common deps
[dependencies]
spirv-std.workspace = true
opencl_std_math_vec-shared = { path = "../opencl_std_math_vec-shared" }

# CPU deps
[target.'cfg(not(target_arch = "spirv"))'.dependencies]
difftest.workspace = true
bytemuck.workspace = true
