// Verify that the `kernel_arguments` linker pass converts the void(void)
// entry stub generated by codegen into a function with proper
// `OpFunctionParameter` instructions for each kernel argument.

// build-pass
// ignore-vulkan1.1
// ignore-vulkan1.2
// ignore-vulkan1.3
// ignore-vulkan1.4
// ignore-spv1.3
// ignore-spv1.4

// compile-flags: -C llvm-args=--disassemble-entry=main
// normalize-stderr-test "OpLine .*\n" -> ""

use spirv_std::spirv;

#[spirv(kernel)]
pub fn main(#[spirv(cross_workgroup)] buf: &mut u32) {
    *buf = 42;
}
